eureka:
  instance:
    hostname: localhost
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

spring:
  application:
    name: zuul-server

zuul:
  routes:
    api-greet:
      path: /api/greet/**
      serviceId: greet-service
    api-user:
      path: /api/user/**
      serviceId: user-service